---
title: Singlepage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
<<<<<<< HEAD
url: https://veramaximiliano.github.io/singlepage/
=======
url: 'https://veramaximiliano.github.io/singlepage'
>>>>>>> Update site
baseurl: ''
